import type { NextPage } from 'next'
import Head from 'next/head'

import { Layout } from "../components/Layout"
import { About } from "../components/About"


const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Pedro Barboza - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <About />

    </Layout>
  )
}

export default Home
